#!/bin/bash

# Rename the input script file to main.py
mv "${PYFILE}" main.py

# Compile the script and save the bytecode to a file
python3 -m compileall -b main.py && mv main.pyc "${PYFILE}c"

# Rename the input script file back to its original name
mv main.py "${PYFILE}"



